# -*- coding: utf-8 -*-
"""
Corrige les accents francais manquants dans generate_memoire_pdf.py.

Regles strictes pour eviter les erreurs :
- Remplace les noms, adjectifs, adverbes non-ambigus.
- Remplace les participes feminins (-ee -> -ee, -ees -> -ees).
- Remplace les infinitifs avec accent.
- NE TOUCHE PAS aux mots ambigus (verbe present vs participe masculin).
- Word boundaries \b protegent les identifiants Python.
"""
from __future__ import annotations
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
TARGET = ROOT / "generate_memoire_pdf.py"

# ----------------------------------------------------------------------------
# Dictionnaire NON-AMBIGU : nom, adjectif, participe feminin, infinitif
# ----------------------------------------------------------------------------
WORD_FIXES: dict[str, str] = {
    # ==== NOMS COMMUNS (non-ambigus avec verbes) ====
    "Resume": "Résumé", "resume": "résumé",
    "Memoire": "Mémoire", "memoire": "mémoire",
    "Methodologie": "Méthodologie", "methodologie": "méthodologie",
    "Modele": "Modèle", "modele": "modèle",
    "Modeles": "Modèles", "modeles": "modèles",
    "Modelisation": "Modélisation", "modelisation": "modélisation",
    "Donnees": "Données", "donnees": "données",
    "Donnee": "Donnée", "donnee": "donnée",
    "Prevision": "Prévision", "prevision": "prévision",
    "Previsions": "Prévisions", "previsions": "prévisions",
    "Decomposition": "Décomposition", "decomposition": "décomposition",
    "Decompositions": "Décompositions", "decompositions": "décompositions",
    "Detection": "Détection", "detection": "détection",
    "Annee": "Année", "annee": "année",
    "Annees": "Années", "annees": "années",
    "Periode": "Période", "periode": "période",
    "Periodes": "Périodes", "periodes": "périodes",
    "Conformite": "Conformité", "conformite": "conformité",
    "Etude": "Étude", "etude": "étude",
    "Etudes": "Études", "etudes": "études",
    "Ecole": "École", "ecole": "école",
    "Ecart": "Écart", "ecart": "écart",
    "Ecarts": "Écarts", "ecarts": "écarts",
    "Echec": "Échec", "echec": "échec",
    "Echecs": "Échecs", "echecs": "échecs",
    "Etat": "État", "etat": "état",
    "Etats": "États", "etats": "états",
    "Enonce": "Énoncé", "enonce": "énoncé",
    "Etape": "Étape", "etape": "étape",
    "Etapes": "Étapes", "etapes": "étapes",
    "Strategie": "Stratégie", "strategie": "stratégie",
    "Strategies": "Stratégies", "strategies": "stratégies",
    "Generation": "Génération", "generation": "génération",
    "Generations": "Générations", "generations": "générations",
    "Reseau": "Réseau", "reseau": "réseau",
    "Reseaux": "Réseaux", "reseaux": "réseaux",
    "Reference": "Référence", "reference": "référence",
    "References": "Références", "references": "références",
    "Selection": "Sélection", "selection": "sélection",
    "Implementation": "Implémentation", "implementation": "implémentation",
    "Quantite": "Quantité", "quantite": "quantité",
    "Quantites": "Quantités", "quantites": "quantités",
    "Qualite": "Qualité", "qualite": "qualité",
    "Qualites": "Qualités", "qualites": "qualités",
    "Stabilite": "Stabilité", "stabilite": "stabilité",
    "Probabilite": "Probabilité", "probabilite": "probabilité",
    "Precision": "Précision", "precision": "précision",
    "Operation": "Opération", "operation": "opération",
    "Operations": "Opérations", "operations": "opérations",
    "Decision": "Décision", "decision": "décision",
    "Decisions": "Décisions", "decisions": "décisions",
    "Cle": "Clé", "cle": "clé",
    "Cles": "Clés", "cles": "clés",
    "Acces": "Accès", "acces": "accès",
    "Apres": "Après", "apres": "après",
    "Pres": "Près",
    "Tres": "Très", "tres": "très",
    "Deja": "Déjà", "deja": "déjà",
    "Decembre": "Décembre", "decembre": "décembre",
    "Fevrier": "Février", "fevrier": "février",
    "Asymetrie": "Asymétrie", "asymetrie": "asymétrie",
    "Asymetries": "Asymétries", "asymetries": "asymétries",
    "Symetrie": "Symétrie", "symetrie": "symétrie",
    "Caracteristique": "Caractéristique", "caracteristique": "caractéristique",
    "Caracteristiques": "Caractéristiques", "caracteristiques": "caractéristiques",
    "Caractere": "Caractère", "caractere": "caractère",
    "Caracteres": "Caractères", "caracteres": "caractères",
    "Heterogeneite": "Hétérogénéité", "heterogeneite": "hétérogénéité",
    "Probleme": "Problème", "probleme": "problème",
    "Problemes": "Problèmes", "problemes": "problèmes",
    "Problematique": "Problématique", "problematique": "problématique",
    "Problematiques": "Problématiques", "problematiques": "problématiques",
    "Systeme": "Système", "systeme": "système",
    "Systemes": "Systèmes", "systemes": "systèmes",
    "Chaine": "Chaîne", "chaine": "chaîne",
    "Chaines": "Chaînes", "chaines": "chaînes",
    "Maitrise": "Maîtrise", "maitrise": "maîtrise",
    "Methode": "Méthode", "methode": "méthode",
    "Methodes": "Méthodes", "methodes": "méthodes",
    "Hypothese": "Hypothèse", "hypothese": "hypothèse",
    "Hypotheses": "Hypothèses", "hypotheses": "hypothèses",
    "These": "Thèse", "these": "thèse",
    "Marche": "Marché", "marche": "marché",
    "Echelle": "Échelle", "echelle": "échelle",
    "Decennie": "Décennie", "decennie": "décennie",
    "Categorie": "Catégorie", "categorie": "catégorie",
    "Categories": "Catégories", "categories": "catégories",
    "Critere": "Critère", "critere": "critère",
    "Criteres": "Critères", "criteres": "critères",
    "Demarche": "Démarche", "demarche": "démarche",
    "Demarches": "Démarches", "demarches": "démarches",
    "Resultat": "Résultat", "resultat": "résultat",
    "Resultats": "Résultats", "resultats": "résultats",
    "Reduction": "Réduction", "reduction": "réduction",
    "Regression": "Régression", "regression": "régression",
    "Reglement": "Règlement", "reglement": "règlement",
    "Regle": "Règle", "regle": "règle",
    "Regles": "Règles", "regles": "règles",
    "Regime": "Régime", "regime": "régime",
    "Regimes": "Régimes", "regimes": "régimes",
    "Region": "Région", "region": "région",
    "Regions": "Régions", "regions": "régions",
    "Bareme": "Barème", "bareme": "barème",
    "Baremes": "Barèmes", "baremes": "barèmes",
    "Comite": "Comité", "comite": "comité",
    "Comites": "Comités", "comites": "comités",
    "Critere": "Critère",
    "Recettes": "Recettes",
    "Aleatoire": "Aléatoire", "aleatoire": "aléatoire",
    "Aleatoires": "Aléatoires", "aleatoires": "aléatoires",
    "Materiau": "Matériau", "materiau": "matériau",
    "Materiel": "Matériel", "materiel": "matériel",
    "Materiels": "Matériels", "materiels": "matériels",
    "Materiaux": "Matériaux", "materiaux": "matériaux",
    "Equipement": "Équipement", "equipement": "équipement",
    "Equipements": "Équipements", "equipements": "équipements",
    "Pluviometrie": "Pluviométrie", "pluviometrie": "pluviométrie",
    "Temperature": "Température", "temperature": "température",
    "Temperatures": "Températures", "temperatures": "températures",
    "Securite": "Sécurité", "securite": "sécurité",
    "Securites": "Sécurités", "securites": "sécurités",
    "Sante": "Santé", "sante": "santé",
    "Frequence": "Fréquence", "frequence": "fréquence",
    "Frequences": "Fréquences", "frequences": "fréquences",
    "Cardinalite": "Cardinalité", "cardinalite": "cardinalité",
    "Colinearite": "Colinéarité", "colinearite": "colinéarité",
    "Linearite": "Linéarité", "linearite": "linéarité",
    "Communaute": "Communauté", "communaute": "communauté",
    "Communautes": "Communautés", "communautes": "communautés",
    "Modalite": "Modalité", "modalite": "modalité",
    "Modalites": "Modalités", "modalites": "modalités",
    "Dualite": "Dualité", "dualite": "dualité",
    "Validite": "Validité", "validite": "validité",
    "Reproductibilite": "Reproductibilité", "reproductibilite": "reproductibilité",
    "Scalabilite": "Scalabilité", "scalabilite": "scalabilité",
    "Disponibilite": "Disponibilité", "disponibilite": "disponibilité",
    "Indisponibilite": "Indisponibilité", "indisponibilite": "indisponibilité",
    "Observabilite": "Observabilité", "observabilite": "observabilité",
    "Significativite": "Significativité", "significativite": "significativité",
    "Honnetete": "Honnêteté", "honnetete": "honnêteté",
    "Causalite": "Causalité", "causalite": "causalité",
    "Theorie": "Théorie", "theorie": "théorie",
    "Theories": "Théories", "theories": "théories",
    "Numerique": "Numérique", "numerique": "numérique",
    "Numeriques": "Numériques", "numeriques": "numériques",
    "Numero": "Numéro", "numero": "numéro",
    "Numeros": "Numéros", "numeros": "numéros",
    "Bibliotheque": "Bibliothèque", "bibliotheque": "bibliothèque",
    "Bibliotheques": "Bibliothèques", "bibliotheques": "bibliothèques",
    "Pretraitement": "Prétraitement", "pretraitement": "prétraitement",
    "Sequence": "Séquence", "sequence": "séquence",
    "Sequences": "Séquences", "sequences": "séquences",
    "Inference": "Inférence", "inference": "inférence",
    "Convergence": "Convergence",
    "Surapprentissage": "Surapprentissage",
    "Entrainement": "Entraînement", "entrainement": "entraînement",
    "Entrainements": "Entraînements", "entrainements": "entraînements",
    "Detail": "Détail", "detail": "détail",
    "Details": "Détails", "details": "détails",
    "Defaut": "Défaut", "defaut": "défaut",
    "Defauts": "Défauts", "defauts": "défauts",
    "Defi": "Défi", "defi": "défi",
    "Defis": "Défis", "defis": "défis",
    "Depot": "Dépôt", "depot": "dépôt",
    "Depots": "Dépôts", "depots": "dépôts",
    "Voute": "Voûte", "voute": "voûte",
    "Foret": "Forêt", "foret": "forêt",
    "Forets": "Forêts", "forets": "forêts",
    "Tete": "Tête", "tete": "tête",
    "Cout": "Coût", "cout": "coût",
    "Couts": "Coûts", "couts": "coûts",
    "Traine": "Traîne", "traine": "traîne",
    "Maitre": "Maître", "maitre": "maître",
    "Maitres": "Maîtres", "maitres": "maîtres",
    "Ingenierie": "Ingénierie", "ingenierie": "ingénierie",
    "Metrique": "Métrique", "metrique": "métrique",
    "Metriques": "Métriques", "metriques": "métriques",
    "Metier": "Métier", "metier": "métier",
    "Metiers": "Métiers", "metiers": "métiers",
    "Mediane": "Médiane", "mediane": "médiane",
    "Medianes": "Médianes", "medianes": "médianes",
    "Categorisation": "Catégorisation", "categorisation": "catégorisation",
    "Parametre": "Paramètre", "parametre": "paramètre",
    "Parametres": "Paramètres", "parametres": "paramètres",
    "Hyperparametre": "Hyperparamètre", "hyperparametre": "hyperparamètre",
    "Hyperparametres": "Hyperparamètres", "hyperparametres": "hyperparamètres",
    "Coeur": "Cœur", "coeur": "cœur",
    "Oeuvre": "Œuvre", "oeuvre": "œuvre",
    "Oeuvres": "Œuvres", "oeuvres": "œuvres",
    "Presence": "Présence", "presence": "présence",
    "Ferie": "Férié", "ferie": "férié",
    "Feries": "Fériés", "feries": "fériés",
    "Demoiselle": "Demoiselle",
    "Universitaire": "Universitaire",  # OK already
    # ==== ADJECTIFS NON-AMBIGUS ====
    "Methodologique": "Méthodologique", "methodologique": "méthodologique",
    "Methodologiques": "Méthodologiques", "methodologiques": "méthodologiques",
    "Operationnel": "Opérationnel", "operationnel": "opérationnel",
    "Operationnelle": "Opérationnelle", "operationnelle": "opérationnelle",
    "Operationnels": "Opérationnels", "operationnels": "opérationnels",
    "Operationnelles": "Opérationnelles", "operationnelles": "opérationnelles",
    "Decisionnel": "Décisionnel", "decisionnel": "décisionnel",
    "Decisionnelle": "Décisionnelle", "decisionnelle": "décisionnelle",
    "Strategique": "Stratégique", "strategique": "stratégique",
    "Strategiques": "Stratégiques", "strategiques": "stratégiques",
    "Generale": "Générale", "generale": "générale",
    "Generales": "Générales", "generales": "générales",
    "Generique": "Générique", "generique": "générique",
    "Generiques": "Génériques", "generiques": "génériques",
    "Categorique": "Catégorique", "categorique": "catégorique",
    "Categoriques": "Catégoriques", "categoriques": "catégoriques",
    "Categorielle": "Catégorielle", "categorielle": "catégorielle",
    "Categorielles": "Catégorielles", "categorielles": "catégorielles",
    "Specifique": "Spécifique", "specifique": "spécifique",
    "Specifiques": "Spécifiques", "specifiques": "spécifiques",
    "Premiere": "Première", "premiere": "première",
    "Premieres": "Premières", "premieres": "premières",
    "Derniere": "Dernière", "derniere": "dernière",
    "Dernieres": "Dernières", "dernieres": "dernières",
    "Deuxieme": "Deuxième", "deuxieme": "deuxième",
    "Troisieme": "Troisième", "troisieme": "troisième",
    "Quatrieme": "Quatrième", "quatrieme": "quatrième",
    "Cinquieme": "Cinquième", "cinquieme": "cinquième",
    "Sixieme": "Sixième", "sixieme": "sixième",
    "Septieme": "Septième", "septieme": "septième",
    "Huitieme": "Huitième", "huitieme": "huitième",
    "Neuvieme": "Neuvième", "neuvieme": "neuvième",
    "Dixieme": "Dixième", "dixieme": "dixième",
    "Centieme": "Centième", "centieme": "centième",
    "Recente": "Récente", "recente": "récente",
    "Recentes": "Récentes", "recentes": "récentes",
    "Recurrent": "Récurrent", "recurrent": "récurrent",
    "Recurrente": "Récurrente", "recurrente": "récurrente",
    "Recurrents": "Récurrents", "recurrents": "récurrents",
    "Recurrentes": "Récurrentes", "recurrentes": "récurrentes",
    "Reelle": "Réelle", "reelle": "réelle",
    "Reelles": "Réelles", "reelles": "réelles",
    "Reel": "Réel", "reel": "réel",
    "Reels": "Réels", "reels": "réels",
    "Concrete": "Concrète", "concrete": "concrète",
    "Concretes": "Concrètes", "concretes": "concrètes",
    "Honnete": "Honnête", "honnete": "honnête",
    "Honnetes": "Honnêtes", "honnetes": "honnêtes",
    "Coherent": "Cohérent", "coherent": "cohérent",
    "Coherente": "Cohérente", "coherente": "cohérente",
    "Coherents": "Cohérents", "coherents": "cohérents",
    "Coherentes": "Cohérentes", "coherentes": "cohérentes",
    "Coherence": "Cohérence", "coherence": "cohérence",
    "Independant": "Indépendant", "independant": "indépendant",
    "Independante": "Indépendante", "independante": "indépendante",
    "Independants": "Indépendants", "independants": "indépendants",
    "Independantes": "Indépendantes", "independantes": "indépendantes",
    "Lineaire": "Linéaire", "lineaire": "linéaire",
    "Lineaires": "Linéaires", "lineaires": "linéaires",
    "Exogene": "Exogène", "exogene": "exogène",
    "Exogenes": "Exogènes", "exogenes": "exogènes",
    "Endogene": "Endogène", "endogene": "endogène",
    "Endogenes": "Endogènes", "endogenes": "endogènes",
    "Heterogene": "Hétérogène", "heterogene": "hétérogène",
    "Heterogenes": "Hétérogènes", "heterogenes": "hétérogènes",
    "Conceptuel": "Conceptuel",
    "Reproductible": "Reproductible",
    "Reproductibles": "Reproductibles",
    "Academique": "Académique", "academique": "académique",
    "Academiques": "Académiques", "academiques": "académiques",
    "Specialisee": "Spécialisée", "specialisee": "spécialisée",
    "Specialisees": "Spécialisées", "specialisees": "spécialisées",
    "Specialise": "Spécialisé", "specialise": "spécialisé",
    "Specialises": "Spécialisés", "specialises": "spécialisés",
    "Geopolitique": "Géopolitique", "geopolitique": "géopolitique",
    "Geopolitiques": "Géopolitiques", "geopolitiques": "géopolitiques",
    "Imprevu": "Imprévu", "imprevu": "imprévu",
    "Imprevus": "Imprévus", "imprevus": "imprévus",
    "Imprevue": "Imprévue", "imprevue": "imprévue",
    "Imprevues": "Imprévues", "imprevues": "imprévues",
    "Numerise": "Numérisé", "numerise": "numérisé",
    "Numerisee": "Numérisée", "numerisee": "numérisée",
    "Insuffisant": "Insuffisant",
    "Insuffisante": "Insuffisante",
    "Insuffisants": "Insuffisants",
    "Insuffisantes": "Insuffisantes",
    "Elevee": "Élevée", "elevee": "élevée",
    "Elevees": "Élevées", "elevees": "élevées",
    "Inferieure": "Inférieure", "inferieure": "inférieure",
    "Inferieures": "Inférieures", "inferieures": "inférieures",
    "Inferieur": "Inférieur", "inferieur": "inférieur",
    "Inferieurs": "Inférieurs", "inferieurs": "inférieurs",
    "Superieure": "Supérieure", "superieure": "supérieure",
    "Superieures": "Supérieures", "superieures": "supérieures",
    "Superieur": "Supérieur", "superieur": "supérieur",
    "Superieurs": "Supérieurs", "superieurs": "supérieurs",
    "Superiorite": "Supériorité", "superiorite": "supériorité",
    "Ulterieur": "Ultérieur", "ulterieur": "ultérieur",
    "Ulterieure": "Ultérieure", "ulterieure": "ultérieure",
    "Ulterieures": "Ultérieures", "ulterieures": "ultérieures",
    "Anterieur": "Antérieur", "anterieur": "antérieur",
    "Anterieure": "Antérieure", "anterieure": "antérieure",
    "Anterieurement": "Antérieurement", "anterieurement": "antérieurement",
    "Posterieur": "Postérieur", "posterieur": "postérieur",
    "Posteriori": "Postériori", "posteriori": "postériori",
    "Reguliere": "Régulière", "reguliere": "régulière",
    "Regulieres": "Régulières", "regulieres": "régulières",
    "Regulier": "Régulier", "regulier": "régulier",
    "Reguliers": "Réguliers", "reguliers": "réguliers",
    "Decevant": "Décevant", "decevant": "décevant",
    "Decevants": "Décevants", "decevants": "décevants",
    "Decevante": "Décevante", "decevante": "décevante",
    "Decevantes": "Décevantes", "decevantes": "décevantes",
    "Pluviometrique": "Pluviométrique", "pluviometrique": "pluviométrique",
    "Meteorologique": "Météorologique", "meteorologique": "météorologique",
    "Meteorologiques": "Météorologiques", "meteorologiques": "météorologiques",
    "Conditionnel": "Conditionnel",
    "Conditionnels": "Conditionnels",
    "Conditionnelle": "Conditionnelle",
    "Conditionnelles": "Conditionnelles",
    "Cumulative": "Cumulative",
    "Negative": "Négative", "negative": "négative",
    "Negatif": "Négatif", "negatif": "négatif",
    "Negatifs": "Négatifs", "negatifs": "négatifs",
    "Negatives": "Négatives", "negatives": "négatives",
    "Positive": "Positive",  # OK
    "Quadrature": "Quadrature",
    "Quantifie": "Quantifié", "quantifie": "quantifié",
    "Quantifiees": "Quantifiées", "quantifiees": "quantifiées",
    "Reformule": "Reformulé", "reformule": "reformulé",
    "Reformulee": "Reformulée", "reformulee": "reformulée",
    "Reformulees": "Reformulées", "reformulees": "reformulées",
    "Electrique": "Électrique", "electrique": "électrique",
    "Electriques": "Électriques", "electriques": "électriques",
    "Economique": "Économique", "economique": "économique",
    "Economiques": "Économiques", "economiques": "économiques",
    "Europeen": "Européen", "europeen": "européen",
    "Europeenne": "Européenne", "europeenne": "européenne",
    "Europeennes": "Européennes", "europeennes": "européennes",
    "Industrielle": "Industrielle",
    "Universelle": "Universelle",
    # ==== ADVERBES ====
    "Generalement": "Généralement", "generalement": "généralement",
    "Specifiquement": "Spécifiquement", "specifiquement": "spécifiquement",
    "Particulierement": "Particulièrement", "particulierement": "particulièrement",
    "Methodologiquement": "Méthodologiquement", "methodologiquement": "méthodologiquement",
    "Operationnellement": "Opérationnellement", "operationnellement": "opérationnellement",
    "Significativement": "Significativement",  # OK
    "Premierement": "Premièrement", "premierement": "premièrement",
    "Deuxiemement": "Deuxièmement", "deuxiemement": "deuxièmement",
    "Troisiemement": "Troisièmement", "troisiemement": "troisièmement",
    "Quatriemement": "Quatrièmement", "quatriemement": "quatrièmement",
    "Cinquiemement": "Cinquièmement", "cinquiemement": "cinquièmement",
    "Reellement": "Réellement", "reellement": "réellement",
    "Recemment": "Récemment", "recemment": "récemment",
    "Regulierement": "Régulièrement", "regulierement": "régulièrement",
    "Honnetement": "Honnêtement", "honnetement": "honnêtement",
    "Concretement": "Concrètement", "concretement": "concrètement",
    "Naturellement": "Naturellement",  # OK
    "Frequemment": "Fréquemment", "frequemment": "fréquemment",
    "Mecaniquement": "Mécaniquement", "mecaniquement": "mécaniquement",
    "Economiquement": "Économiquement", "economiquement": "économiquement",
    # ==== INFINITIFS NON-AMBIGUS ====
    "Realiser": "Réaliser", "realiser": "réaliser",
    "Reformuler": "Reformuler",
    "Reduire": "Réduire", "reduire": "réduire",
    "Repondre": "Répondre", "repondre": "répondre",
    "Verifier": "Vérifier", "verifier": "vérifier",
    "Demontrer": "Démontrer", "demontrer": "démontrer",
    "Depasser": "Dépasser", "depasser": "dépasser",
    "Améliorer": "Améliorer", "ameliorer": "améliorer",
    "Determiner": "Déterminer", "determiner": "déterminer",
    "Decider": "Décider", "decider": "décider",
    "Definir": "Définir", "definir": "définir",
    "Etudier": "Étudier", "etudier": "étudier",
    "Generer": "Générer", "generer": "générer",
    "Decoder": "Décoder", "decoder": "décoder",
    "Decouvrir": "Découvrir", "decouvrir": "découvrir",
    "Decouper": "Découper", "decouper": "découper",
    "Reperer": "Repérer", "reperer": "repérer",
    "Detecter": "Détecter", "detecter": "détecter",
    "Eviter": "Éviter", "eviter": "éviter",
    "Eclairer": "Éclairer", "eclairer": "éclairer",
    "Evaluer": "Évaluer", "evaluer": "évaluer",
    "Reagir": "Réagir", "reagir": "réagir",
    "Reformuler": "Reformuler",
    "Recapituler": "Récapituler", "recapituler": "récapituler",
    "Renforcer": "Renforcer",
    "Resoudre": "Résoudre", "resoudre": "résoudre",
    # ==== PARTICIPES FEMININS (-ee, -ees) NON-AMBIGUS ====
    "Realisee": "Réalisée", "realisee": "réalisée",
    "Realisees": "Réalisées", "realisees": "réalisées",
    "Presentee": "Présentée", "presentee": "présentée",
    "Presentees": "Présentées", "presentees": "présentées",
    "Confrontee": "Confrontée", "confrontee": "confrontée",
    "Confrontees": "Confrontées", "confrontees": "confrontées",
    "Documentee": "Documentée", "documentee": "documentée",
    "Documentees": "Documentées", "documentees": "documentées",
    "Calculee": "Calculée", "calculee": "calculée",
    "Calculees": "Calculées", "calculees": "calculées",
    "Mesuree": "Mesurée", "mesuree": "mesurée",
    "Mesurees": "Mesurées", "mesurees": "mesurées",
    "Selectionnee": "Sélectionnée", "selectionnee": "sélectionnée",
    "Selectionnees": "Sélectionnées", "selectionnees": "sélectionnées",
    "Implementee": "Implémentée", "implementee": "implémentée",
    "Implementees": "Implémentées", "implementees": "implémentées",
    "Identifiee": "Identifiée", "identifiee": "identifiée",
    "Identifiees": "Identifiées", "identifiees": "identifiées",
    "Verifiee": "Vérifiée", "verifiee": "vérifiée",
    "Verifiees": "Vérifiées", "verifiees": "vérifiées",
    "Justifiee": "Justifiée", "justifiee": "justifiée",
    "Justifiees": "Justifiées", "justifiees": "justifiées",
    "Confirmee": "Confirmée", "confirmee": "confirmée",
    "Confirmees": "Confirmées", "confirmees": "confirmées",
    "Determinee": "Déterminée", "determinee": "déterminée",
    "Determinees": "Déterminées", "determinees": "déterminées",
    "Modelisee": "Modélisée", "modelisee": "modélisée",
    "Modelisees": "Modélisées", "modelisees": "modélisées",
    "Realisee": "Réalisée",
    "Limitee": "Limitée", "limitee": "limitée",
    "Limitees": "Limitées", "limitees": "limitées",
    "Decoupee": "Découpée", "decoupee": "découpée",
    "Decoupees": "Découpées", "decoupees": "découpées",
    "Documentees": "Documentées",
    "Performante": "Performante",  # OK
    "Performantes": "Performantes",  # OK
    "Detaillee": "Détaillée", "detaillee": "détaillée",
    "Detaillees": "Détaillées", "detaillees": "détaillées",
    "Reduite": "Réduite", "reduite": "réduite",
    "Reduites": "Réduites", "reduites": "réduites",
    "Tracee": "Tracée", "tracee": "tracée",
    "Tracees": "Tracées", "tracees": "tracées",
    "Ancree": "Ancrée", "ancree": "ancrée",
    "Adaptee": "Adaptée", "adaptee": "adaptée",
    "Adaptees": "Adaptées", "adaptees": "adaptées",
    "Inadaptee": "Inadaptée", "inadaptee": "inadaptée",
    "Inadaptees": "Inadaptées", "inadaptees": "inadaptées",
    "Reformulee": "Reformulée",
    "Optimisee": "Optimisée", "optimisee": "optimisée",
    "Optimisees": "Optimisées", "optimisees": "optimisées",
    "Synthetisee": "Synthétisée", "synthetisee": "synthétisée",
    "Conjuguee": "Conjuguée", "conjuguee": "conjuguée",
    "Centralisee": "Centralisée", "centralisee": "centralisée",
    "Centralisees": "Centralisées", "centralisees": "centralisées",
    "Decentralisee": "Décentralisée", "decentralisee": "décentralisée",
    "Levee": "Levée", "levee": "levée",
    "Levees": "Levées", "levees": "levées",
    "Articulee": "Articulée", "articulee": "articulée",
    "Articulees": "Articulées", "articulees": "articulées",
    "Connectee": "Connectée", "connectee": "connectée",
    "Connectees": "Connectées", "connectees": "connectées",
    "Deconnectee": "Déconnectée", "deconnectee": "déconnectée",
    "Deconnectees": "Déconnectées", "deconnectees": "déconnectées",
    "Decouplee": "Découplée", "decouplee": "découplée",
    "Decouplees": "Découplées", "decouplees": "découplées",
    "Insuree": "Insurée",
    "Calibree": "Calibrée", "calibree": "calibrée",
    "Calibrees": "Calibrées", "calibrees": "calibrées",
    "Surveillee": "Surveillée", "surveillee": "surveillée",
    "Surveillees": "Surveillées", "surveillees": "surveillées",
    "Sourcee": "Sourcée", "sourcee": "sourcée",
    "Chiffree": "Chiffrée", "chiffree": "chiffrée",
    "Chiffrees": "Chiffrées", "chiffrees": "chiffrées",
    "Encodee": "Encodée", "encodee": "encodée",
    "Encodees": "Encodées", "encodees": "encodées",
    "Niveau": "Niveau",  # OK
    "Acceptee": "Acceptée", "acceptee": "acceptée",
    "Validee": "Validée", "validee": "validée",
    "Validees": "Validées", "validees": "validées",
    "Restee": "Restée", "restee": "restée",
    "Restees": "Restées", "restees": "restées",
    "Inseree": "Insérée", "inseree": "insérée",
    "Inserees": "Insérées", "inserees": "insérées",
    "Sourcee": "Sourcée",
    "Concentree": "Concentrée", "concentree": "concentrée",
    "Concentrees": "Concentrées", "concentrees": "concentrées",
    "Evoquee": "Évoquée", "evoquee": "évoquée",
    "Evoquees": "Évoquées", "evoquees": "évoquées",
    "Renforcee": "Renforcée", "renforcee": "renforcée",
    "Renforcees": "Renforcées", "renforcees": "renforcées",
    "Concurrence": "Concurrencé", "concurrence": "concurrencé",  # ambig but rare
    # ==== PRÉFIXE é- (initial accent en é) ====
    "Etablissement": "Établissement", "etablissement": "établissement",
    "Etablissements": "Établissements", "etablissements": "établissements",
    "Etudiant": "Étudiant", "etudiant": "étudiant",
    "Etudiants": "Étudiants", "etudiants": "étudiants",
    "Edition": "Édition", "edition": "édition",
    "Editions": "Éditions", "editions": "éditions",
    "Editeur": "Éditeur", "editeur": "éditeur",
    "Ensemble": "Ensemble",  # OK (no accent)
    "Enseignement": "Enseignement",  # OK
    "Energie": "Énergie", "energie": "énergie",
    "Energetique": "Énergétique", "energetique": "énergétique",
    "Energetiques": "Énergétiques", "energetiques": "énergétiques",
    "Egard": "Égard", "egard": "égard",
    "Eveille": "Éveillé",
    "Echeance": "Échéance", "echeance": "échéance",
    "Echeances": "Échéances", "echeances": "échéances",
    # ==== MOTS PROPRES (auteurs, lieux) — NON modifiés ====
    # (deja correctement en l'etat dans la biblio)
    # ==== Mots residuels importants ====
    "Avancee": "Avancée", "avancee": "avancée",
    "Avancees": "Avancées", "avancees": "avancées",
    "Communique": "Communiqué", "communique": "communiqué",
    "Communiquee": "Communiquée", "communiquee": "communiquée",
    "Negocies": "Négociés", "negocies": "négociés",
    "Negociee": "Négociée", "negociee": "négociée",
    "Negociees": "Négociées", "negociees": "négociées",
    "Decrites": "Décrites", "decrites": "décrites",
    "Decrite": "Décrite", "decrite": "décrite",
    "Decrits": "Décrits", "decrits": "décrits",
    "Documentes": "Documentés", "documentes": "documentés",
    "Realises": "Réalisés", "realises": "réalisés",
    "Detailes": "Détaillés",  # typo possible
    "Detaille": "Détaillé", "detaille": "détaillé",
    "Detailles": "Détaillés", "detailles": "détaillés",
    "Ameliorations": "Améliorations", "ameliorations": "améliorations",
    "Amelioration": "Amélioration", "amelioration": "amélioration",
    "Evaluation": "Évaluation", "evaluation": "évaluation",
    "Evaluations": "Évaluations", "evaluations": "évaluations",
    "Evolution": "Évolution", "evolution": "évolution",
    "Evolutions": "Évolutions", "evolutions": "évolutions",
    "Presentation": "Présentation", "presentation": "présentation",
    "Presentations": "Présentations", "presentations": "présentations",
    "Prevoyances": "Prévoyances",
    "Prediction": "Prédiction", "prediction": "prédiction",
    "Predictions": "Prédictions", "predictions": "prédictions",
    "Predictif": "Prédictif", "predictif": "prédictif",
    "Predictive": "Prédictive", "predictive": "prédictive",
    "Predictifs": "Prédictifs", "predictifs": "prédictifs",
    "Predictives": "Prédictives", "predictives": "prédictives",
    "Rapprochement": "Rapprochement",  # OK
    "Reapprovisionnement": "Réapprovisionnement", "reapprovisionnement": "réapprovisionnement",
    "Reapprovisionnements": "Réapprovisionnements", "reapprovisionnements": "réapprovisionnements",
    "Restitution": "Restitution",  # OK
    "Restitue": "Restitué", "restitue": "restitué",
    "Restituee": "Restituée", "restituee": "restituée",
    "Restituees": "Restituées", "restituees": "restituées",
    "Restitues": "Restitués", "restitues": "restitués",
    "Reformulation": "Reformulation",  # OK
    "Reformulations": "Reformulations",
    "Recommandation": "Recommandation",  # OK
    "Recommandations": "Recommandations",
    "Recommandee": "Recommandée", "recommandee": "recommandée",
    "Recommandees": "Recommandées", "recommandees": "recommandées",
    # ==== PROBLEMATIQUES ET CRITIQUES SPECIFIQUES OBSERVÉS ====
    "Realiste": "Réaliste", "realiste": "réaliste",
    "Realistes": "Réalistes", "realistes": "réalistes",
    "Diebold-Mariano": "Diebold-Mariano",  # OK
    "Conformite": "Conformité",  # done
    "Pseudonymisation": "Pseudonymisation",
    # ==== MOTS CULTURELS ====
    "Calendrier": "Calendrier",  # OK
    "Calendriers": "Calendriers",
    "Hivernal": "Hivernal", "hivernal": "hivernal",
    "Estival": "Estival", "estival": "estival",
    "Estivale": "Estivale",
    # ==== INFRA / TECH (deja OK majoritairement) ====
    "MLflow": "MLflow",  # OK (English)
    "PostgreSQL": "PostgreSQL",
    "FastAPI": "FastAPI",
    "Streamlit": "Streamlit",
    "Plotly": "Plotly",
    "Evidently": "Evidently",
    "Docker": "Docker",
    "Prefect": "Prefect",
    "Airflow": "Airflow",
    "Grafana": "Grafana",
    "Prometheus": "Prometheus",
    "Sentry": "Sentry",
    "Pydantic": "Pydantic",
    "Nginx": "Nginx",
    # ==== AUTRES OBSERVÉS ====
    "Lecteur": "Lecteur",  # OK
    "Lecteurs": "Lecteurs",
    "Lecture": "Lecture",  # OK
    "Pretendu": "Prétendu", "pretendu": "prétendu",
    "Pretexte": "Prétexte", "pretexte": "prétexte",
    "Preponderante": "Prépondérante", "preponderante": "prépondérante",
    "Preponderants": "Prépondérants", "preponderants": "prépondérants",
    "Premium": "Premium",  # OK
    "Conseille": "Conseillé",  # adjectif participe — laisse ambigu
    "Conseillee": "Conseillée", "conseillee": "conseillée",
    "Conseillees": "Conseillées", "conseillees": "conseillées",
    "Forge": "Forgé",  # ambig
    "Forgee": "Forgée", "forgee": "forgée",
    "Esperance": "Espérance", "esperance": "espérance",
    "Mecanique": "Mécanique", "mecanique": "mécanique",
    "Mecaniques": "Mécaniques", "mecaniques": "mécaniques",
    "Veritablement": "Véritablement", "veritablement": "véritablement",
    "Veritable": "Véritable", "veritable": "véritable",
    "Verite": "Vérité", "verite": "vérité",
    "Verites": "Vérités", "verites": "vérités",
    "Apprends": "Apprends",  # OK
    "Acceptable": "Acceptable",  # OK
    "Acceptables": "Acceptables",
    "Comportement": "Comportement",  # OK
    "Comportements": "Comportements",
    # Termes specifiques au mémoire
    "Niveau": "Niveau", "Niveaux": "Niveaux",
    "Tableau": "Tableau", "Tableaux": "Tableaux",  # OK
    "Figure": "Figure", "Figures": "Figures",  # OK
    "Synthese": "Synthèse", "synthese": "synthèse",
    "Syntheses": "Synthèses", "syntheses": "synthèses",
    "Synthetique": "Synthétique", "synthetique": "synthétique",
    "Synthetiques": "Synthétiques", "synthetiques": "synthétiques",
    "Recente": "Récente",  # done
    "Procedure": "Procédure", "procedure": "procédure",
    "Procedures": "Procédures", "procedures": "procédures",
    "Voila": "Voilà", "voila": "voilà",
    # === Cas critiques restant identifies ===
    "etre": "être",
    "Etre": "Être",
    "completude": "complétude",
    "Completude": "Complétude",
    "ete": "été",  # participe passe de etre - non ambigu
    # ATTENTION: "complete" -> ambigu (verbe completer vs adjectif complete)
    # SKIP: complete
    # ATTENTION: "documente" -> ambigu, SKIP
    # ATTENTION: "calcule" -> ambigu, SKIP
    # ATTENTION: "presente" -> ambigu MAIS deux formes valides ont accent ("présente" verbe ET "présenté" participe)
    # SKIP presente sg, garder presentee feminin
    # ATTENTION: "developpe", "augmente", "diminue" -> ambigu, SKIP
    "developpe": "développé",  # majoritairement participe dans memoire
    "developpee": "développée",
    "developpes": "développés", "developpees": "développées",
    "developpement": "développement",
    "developpements": "développements",
    "Developpement": "Développement",
    "Developpements": "Développements",
    "decembre": "décembre",  # already
    "Aout": "Août", "aout": "août",
    "Juillet": "Juillet",
    "Septembre": "Septembre",
    "Novembre": "Novembre",
    "Octobre": "Octobre",
    "Janvier": "Janvier",
    "Mai": "Mai",
    "Mars": "Mars",
    "Avril": "Avril",
    "Juin": "Juin",
    # ==== VERBES AVEC É INITIAL (3e pers sg = participe masc sg) ====
    # Pour ces verbes, le é initial est present aussi bien au present qu'au participe.
    "ameliore": "améliore", "Ameliore": "Améliore",
    "ameliores": "améliorés", "Ameliores": "Améliorés",
    "amelioree": "améliorée", "Amelioree": "Améliorée",
    "ameliorees": "améliorées", "Ameliorees": "Améliorées",
    "ameliorent": "améliorent", "Ameliorent": "Améliorent",
    "ameliorant": "améliorant", "Ameliorant": "Améliorant",
    "ameliorera": "améliorera", "amelioreraient": "amélioreraient",
    "repond": "répond", "Repond": "Répond",
    "repondent": "répondent", "Repondent": "Répondent",
    "repondre": "répondre", "Repondre": "Répondre",
    "repondu": "répondu", "repondue": "répondue",
    "depasse": "dépasse", "Depasse": "Dépasse",
    "depassent": "dépassent", "Depassent": "Dépassent",
    "depassant": "dépassant", "Depassant": "Dépassant",
    "depassement": "dépassement", "Depassement": "Dépassement",
    "depasses": "dépassés", "depassees": "dépassées",
    "depassee": "dépassée", "Depassee": "Dépassée",
    "reduit": "réduit", "Reduit": "Réduit",
    "reduits": "réduits", "reduite": "réduite", "reduites": "réduites",
    "reduisent": "réduisent", "reduise": "réduise",
    "reduira": "réduira", "reduiront": "réduiront",
    "reduirait": "réduirait", "reduiraient": "réduiraient",
    "demontre": "démontre", "Demontre": "Démontre",
    "demontrent": "démontrent",
    "demontrant": "démontrant",
    "demontree": "démontrée", "demontrees": "démontrées",
    "demontres": "démontrés",
    "demonstration": "démonstration",
    "demonstrations": "démonstrations",
    "emerge": "émerge", "Emerge": "Émerge",
    "emergent": "émergent", "Emergent": "Émergent",
    "emerger": "émerger", "emergeant": "émergeant",
    "emergence": "émergence", "Emergence": "Émergence",
    "emergente": "émergente", "emergentes": "émergentes",
    "reunie": "réunie", "reunies": "réunies",
    "reunis": "réunis", "reuni": "réuni",
    "reunion": "réunion", "Reunion": "Réunion",
    "reussi": "réussi", "Reussi": "Réussi",
    "reussie": "réussie", "reussis": "réussis", "reussies": "réussies",
    "reussite": "réussite", "Reussite": "Réussite",
    "reussites": "réussites",
    "emis": "émis", "emise": "émise", "emises": "émises",
    "emission": "émission", "emissions": "émissions",
    "ecrit": "écrit", "Ecrit": "Écrit",
    "ecrits": "écrits", "ecrite": "écrite", "ecrites": "écrites",
    "ecrire": "écrire", "Ecrire": "Écrire",
    "ecriture": "écriture", "ecritures": "écritures",
    "elimine": "éliminé", "eliminee": "éliminée",
    "eliminer": "éliminer", "elimination": "élimination",
    "eliminees": "éliminées", "elimines": "éliminés",
    "ecarte": "écarté", "ecartee": "écartée",
    "ecartes": "écartés", "ecartees": "écartées",
    "echange": "échange", "Echange": "Échange",
    "echanges": "échanges", "Echanges": "Échanges",
    "evidente": "évidente", "evidemment": "évidemment",
    "evidence": "évidence",  # OK (no accent needed for spelling rule)
    "epoque": "époque", "Epoque": "Époque",
    "epoques": "époques",
    "epuiser": "épuiser", "epuise": "épuisé",
    "ecologique": "écologique",
    "energetique": "énergétique",
    "energetiques": "énergétiques",
    # ==== PARTICIPES FÉMININS ET PLURIELS NON-AMBIGUS ====
    "structuree": "structurée", "Structuree": "Structurée",
    "structurees": "structurées", "Structurees": "Structurées",
    "nettoyee": "nettoyée", "nettoyees": "nettoyées",
    "Nettoyee": "Nettoyée", "Nettoyees": "Nettoyées",
    "portees": "portées", "Portees": "Portées",
    "portee": "portée", "Portee": "Portée",
    "observees": "observées", "Observees": "Observées",
    "observee": "observée", "Observee": "Observée",
    "etudiees": "étudiées", "Etudiees": "Étudiées",
    "etudiee": "étudiée", "Etudiee": "Étudiée",
    "consolidees": "consolidées", "Consolidees": "Consolidées",
    "consolidee": "consolidée", "Consolidee": "Consolidée",
    "consultees": "consultées", "consultee": "consultée",
    "exposees": "exposées", "exposee": "exposée",
    "comparees": "comparées", "comparee": "comparée",
    "Comparees": "Comparées", "Comparee": "Comparée",
    "agreee": "agréée", "agreees": "agréées",
    "agregee": "agrégée", "agregees": "agrégées",
    "agreges": "agrégés", "agreges": "agrégés",
    "agreger": "agréger", "agregation": "agrégation",
    "Agregee": "Agrégée", "Agregees": "Agrégées",
    "Agregation": "Agrégation",
    "agrege": "agrégé",
    "agregee": "agrégée",
    "filtrees": "filtrées", "filtree": "filtrée",
    "encodees": "encodées", "encodee": "encodée",
    "operees": "opérées", "operee": "opérée",
    "Operees": "Opérées", "Operee": "Opérée",
    "anonymisees": "anonymisées", "anonymisee": "anonymisée",
    "Anonymisee": "Anonymisée",
    "publiees": "publiées", "publiee": "publiée",
    "Publiees": "Publiées", "Publiee": "Publiée",
    "definies": "définies", "definie": "définie",
    "Definies": "Définies", "Definie": "Définie",
    "decrites": "décrites", "decrite": "décrite",
    "Decrites": "Décrites", "Decrite": "Décrite",
    "consacree": "consacrée", "consacrees": "consacrées",
    "Consacree": "Consacrée", "Consacrees": "Consacrées",
    "associee": "associée", "associees": "associées",
    "Associee": "Associée", "Associees": "Associées",
    "abordee": "abordée", "abordees": "abordées",
    "Abordee": "Abordée", "Abordees": "Abordées",
    "explicitee": "explicitée", "explicitees": "explicitées",
    "evoquee": "évoquée", "evoquees": "évoquées",
    "explorees": "explorées", "exploree": "explorée",
    "Explorees": "Explorées",
    "envisagees": "envisagées", "envisagee": "envisagée",
    "Envisagee": "Envisagée", "Envisagees": "Envisagées",
    "augmentees": "augmentées", "Augmentees": "Augmentées",
    "decoulees": "découlées", "decoulent": "découlent",
    "Decoulent": "Découlent",
    "decoule": "découle", "Decoule": "Découle",
    "ecartees": "écartées", "ecartee": "écartée",
    "echelonnees": "échelonnées", "echelonnee": "échelonnée",
    "etablissees": "établies", "etablissee": "établie",
    "etablies": "établies", "etablie": "établie",
    "Etablies": "Établies", "Etablie": "Établie",
    "etablis": "établis", "etabli": "établi",
    "Etablis": "Établis", "Etabli": "Établi",
    "etablissement": "établissement",  # already
    "verifiees": "vérifiées",  # already
    "verifie": "vérifié", "Verifie": "Vérifié",
    "verifies": "vérifiés", "Verifies": "Vérifiés",
    "vegetale": "végétale", "vegetales": "végétales",
    "vegetal": "végétal",
    # ==== NOMS SUPPLEMENTAIRES ====
    "unite": "unité", "Unite": "Unité",
    "unites": "unités", "Unites": "Unités",
    "derive": "dérive", "Derive": "Dérive",
    "derives": "dérives", "Derives": "Dérives",
    "Inserer": "Insérer", "inserer": "insérer",
    "inseree": "insérée",
    "Echantillon": "Échantillon", "echantillon": "échantillon",
    "Echantillons": "Échantillons", "echantillons": "échantillons",
    "Echantillonnage": "Échantillonnage",
    "Element": "Élément", "element": "élément",
    "Elements": "Éléments", "elements": "éléments",
    "Elevation": "Élévation", "elevation": "élévation",
    "Examen": "Examen", "examens": "examens",  # OK
    "Excecution": "Exécution",  # typo possible
    "Execution": "Exécution", "execution": "exécution",
    "Executions": "Exécutions", "executions": "exécutions",
    "executer": "exécuter", "executes": "exécutés",
    "Executer": "Exécuter",
    "executees": "exécutées", "executee": "exécutée",
    "execute": "exécute",  # 3e pers sg + participe : accent é initial conserve
    "Energie": "Énergie",  # already
    "energie": "énergie", "energies": "énergies",
    "Energetique": "Énergétique", "energetique": "énergétique",
    "Enumeration": "Énumération",
    "Equipe": "Équipe", "equipe": "équipe",
    "Equipes": "Équipes", "equipes": "équipes",
    "Equation": "Équation", "equation": "équation",
    "Equations": "Équations", "equations": "équations",
    "Equilibre": "Équilibre",  # OK
    "Etranger": "Étranger", "etranger": "étranger",
    "Etrangere": "Étrangère", "etrangere": "étrangère",
    "Etranges": "Étrangers",
    "Eveil": "Éveil", "eveil": "éveil",
    "Eveille": "Éveillé", "eveille": "éveillé",
    "Eveilles": "Éveillés", "eveilles": "éveillés",
    "Ange": "Ange",
    # === LISTE FINALE ===
    "autoregressif": "autorégressif", "Autoregressif": "Autorégressif",
    "autoregressive": "autorégressive", "Autoregressive": "Autorégressive",
    "autoregressifs": "autorégressifs", "Autoregressifs": "Autorégressifs",
    "autoregressives": "autorégressives", "Autoregressives": "Autorégressives",
    "autoregression": "autorégression", "Autoregression": "Autorégression",
    "Decoulent": "Découlent",
    "integrant": "intégrant", "Integrant": "Intégrant",
    "integration": "intégration", "Integration": "Intégration",
    "integral": "intégral", "Integral": "Intégral",
    "integrale": "intégrale", "integrales": "intégrales",
    "integralement": "intégralement",
    "interpretable": "interprétable", "interpretables": "interprétables",
    "interpretabilite": "interprétabilité",
    "interpretation": "interprétation",
    "interprete": "interprété",  # ambig but usu participe
    "interpretee": "interprétée", "interpretees": "interprétées",
    "interpretes": "interprétés",
    "Interpretation": "Interprétation",
    "Quotidien": "Quotidien",  # OK
    "Quotidienne": "Quotidienne",
    "quotidienne": "quotidienne", "quotidiennes": "quotidiennes",
    "Conformite": "Conformité",  # done
    "decentralise": "décentralisé", "decentralisee": "décentralisée",
    "automatise": "automatisé", "automatisee": "automatisée",
    "automatisees": "automatisées", "automatises": "automatisés",
    "Automatise": "Automatisé", "Automatisee": "Automatisée",
    "Automatisation": "Automatisation",  # OK
    "Pseudo-randomisee": "Pseudo-randomisée",
    "Carte": "Carte",  # OK
    "Cartes": "Cartes",
    "Carre": "Carré", "carre": "carré",
    "Carres": "Carrés", "carres": "carrés",
    "Carree": "Carrée",
    "Carriere": "Carrière", "carriere": "carrière",
    "Carrieres": "Carrières", "carrieres": "carrières",
    "Operee": "Opérée", "operee": "opérée",
    "Operees": "Opérées", "operees": "opérées",
    "Negligee": "Négligée", "negligee": "négligée",
    "negligeable": "négligeable", "negligeables": "négligeables",
    "Negliger": "Négliger", "negliger": "négliger",
    "neglige": "négligé",
    # mots avec accents internes (-ère, -ier, etc.)
    "Premiere": "Première", "Premieres": "Premières",  # already
    "Identifiable": "Identifiable",  # OK
    "identifiable": "identifiable", "identifiables": "identifiables",
    "Particuliere": "Particulière", "particuliere": "particulière",
    "Particulieres": "Particulières", "particulieres": "particulières",
    "Entiere": "Entière", "entiere": "entière",
    "Entierement": "Entièrement", "entierement": "entièrement",
    "Entieres": "Entières", "entieres": "entières",
    "Manieres": "Manières", "manieres": "manières",
    "Maniere": "Manière", "maniere": "manière",
    "Materiellement": "Matériellement",
    "Materielle": "Matérielle", "materielle": "matérielle",
    "Materielles": "Matérielles", "materielles": "matérielles",
    "Familiere": "Familière", "familiere": "familière",
    "familiarite": "familiarité",
    "Entreprises": "Entreprises",  # OK
    "Entreprise": "Entreprise",  # OK
    "Entrepreneur": "Entrepreneur",  # OK
    "Plenier": "Plénier",
    "Pleniere": "Plénière",
    "Selecteur": "Sélecteur", "selecteur": "sélecteur",
    "Selectionnement": "Sélectionnement",
    "Selectionne": "Sélectionné", "selectionne": "sélectionné",
    "Selectionnes": "Sélectionnés", "selectionnes": "sélectionnés",
    "Selectivite": "Sélectivité", "selectivite": "sélectivité",
    # Quelques accents grave
    "Dela": "Delà",  # ATTENTION: ambig avec abbreviation
    "Au-dela": "Au-delà", "au-dela": "au-delà",
    "Voie": "Voie",  # OK
    "voies": "voies",  # OK
    "Cere": "Cère",  # not used
    "Vis-a-vis": "Vis-à-vis", "vis-a-vis": "vis-à-vis",
    # Quelques specifiques mémoire
    "Echelonnee": "Échelonnée", "echelonnee": "échelonnée",
    "Echelonner": "Échelonner",
    "Empirique": "Empirique",  # OK
    "empiriquement": "empiriquement",  # OK
    "Empirisme": "Empirisme",  # OK
    "Energie": "Énergie",
    "Excepte": "Excepté", "excepte": "excepté",
    "Exceptee": "Exceptée",
    "Exceptionnel": "Exceptionnel",  # OK
    "Exceptionnels": "Exceptionnels",
    "exceptionnelle": "exceptionnelle",  # OK
    "Exceptionnelle": "Exceptionnelle",
    "Exceptionnelles": "Exceptionnelles",  # OK
    "Geometrique": "Géométrique", "geometrique": "géométrique",
    "geometrie": "géométrie",
    "Industries": "Industries",  # OK
    "Industrie": "Industrie",
    "industrie": "industrie", "industries": "industries",
    "Inversement": "Inversement",  # OK (no accent)
    "Iteratif": "Itératif", "iteratif": "itératif",
    "Iterative": "Itérative", "iterative": "itérative",
    "Iteratives": "Itératives", "iteratives": "itératives",
    "Iteratifs": "Itératifs", "iteratifs": "itératifs",
    "Iteration": "Itération", "iteration": "itération",
    "Iterations": "Itérations", "iterations": "itérations",
    "iteree": "itérée", "iterees": "itérées",
    "iteres": "itérés", "itere": "itéré",
    # Statistiques
    "Heteroscedasticite": "Hétéroscédasticité",
    "Hierarchique": "Hiérarchique", "hierarchique": "hiérarchique",
    "Hierarchiques": "Hiérarchiques", "hierarchiques": "hiérarchiques",
    "Hierarchie": "Hiérarchie", "hierarchie": "hiérarchie",
    "Memoire": "Mémoire",  # done
    "Theoreme": "Théorème", "theoreme": "théorème",
    "Theoremes": "Théorèmes", "theoremes": "théorèmes",
    "Operande": "Opérande", "operande": "opérande",
    "Operandes": "Opérandes", "operandes": "opérandes",
    "Operationnels": "Opérationnels",  # done
    "Confondu": "Confondu",  # OK
    "Confondue": "Confondue",
    "Confondus": "Confondus",  # OK
    "Confondues": "Confondues",
    "etapes": "étapes",  # already
    "interieur": "intérieur", "Interieur": "Intérieur",
    "interieure": "intérieure",
    "exterieur": "extérieur", "Exterieur": "Extérieur",
    "exterieurs": "extérieurs", "exterieures": "extérieures",
    "exterieure": "extérieure", "Exterieurs": "Extérieurs",
    "exterieures": "extérieures",
    "Mediocre": "Médiocre", "mediocre": "médiocre",
    "Mediocrement": "Médiocrement",
    "Mediocres": "Médiocres", "mediocres": "médiocres",
    # Mots simples manquants
    "Operationnelles": "Opérationnelles",  # done
    "Operationnel": "Opérationnel",  # done
    "Operer": "Opérer", "operer": "opérer",
    "Opposer": "Opposer",  # OK
    "Verification": "Vérification", "verification": "vérification",
    "Verifications": "Vérifications", "verifications": "vérifications",
    "Cooperation": "Coopération", "cooperation": "coopération",
    "Cooperations": "Coopérations",
    "Conferer": "Conférer", "conferer": "conférer",
    "Confere": "Confère",  # verbe 3e
    "Conferes": "Conférés", "conferees": "conférées",
    "Conferee": "Conférée",
    "Conforme": "Conforme",  # OK
    "conformement": "conformément", "Conformement": "Conformément",
    "Considere": "Considère",  # verbe 3e
    "Considerent": "Considèrent",  # 3e plur
    "considererait": "considérerait",
    "Considere": "Considère",
    "considere": "considère",  # verbe 3e (accent E grave initial reste comme é initial dans considérer)
    # WAIT: "considere" est ambig (verbe present ou participe)
    # On choisit verbe (3e pers), valid aussi pour participe (sans é final)
    # Mais en realite "considéré" participe est plus frequent dans memoire
    "considererait": "considérerait",
    "concluant": "concluant",  # OK
    # Fin
    "Indeterminee": "Indéterminée", "indeterminee": "indéterminée",
    "Indetermine": "Indéterminé",
    "Indetermines": "Indéterminés",
    "decentralise": "décentralisé",
    "Decentralise": "Décentralisé",
    "Decentralisee": "Décentralisée",
    "Decentralisees": "Décentralisées",
    "Couvre": "Couvre",  # OK (verbe sans accent)
    "Couvrant": "Couvrant",  # OK
    "Couvert": "Couvert",  # OK
    "couvertures": "couvertures",  # OK
}

# ----------------------------------------------------------------------------
# Preposition "a" -> "a" : approche par sentinels pour proteger l'auxiliaire avoir
# ----------------------------------------------------------------------------
# Verbes au passe compose (3e pers sg) ou tournures ou "a" est l'auxiliaire
# avoir et doit rester sans accent.
AVOIR_FOLLOWERS = [
    # participes passes courants apres "a"/"a "
    "ete", "été", "fait", "permis", "produit", "porte", "porté", "domine", "dominé",
    "confirme", "confirmé", "identifie", "identifié", "livre", "livré",
    "deja", "déjà", "integre", "intégré", "articule", "articulé",
    "augmente", "augmenté", "vise", "visé", "entrepris", "montre", "montré",
    "developpe", "développé", "concu", "conçu", "abouti", "donne", "donné",
    "atteint", "consiste", "constitue", "constitué", "permis",
    "transmis", "remis", "ouvert", "remplace", "remplacé",
    "mis", "ajoute", "ajouté", "retire", "retiré",
    "produit", "explique", "expliqué", "presente", "présenté", "indique", "indiqué",
    "valide", "validé", "evolue", "évolué", "evolu", "obtenu",
    "deploye", "déployé", "implemente", "implémenté",
    "modifie", "modifié", "supprime", "supprimé", "cree", "créé",
    "rapporte", "rapporté", "decide", "décidé", "choisi", "selectionne", "sélectionné",
    "consulte", "consulté", "analyse", "analysé",
    "demontre", "démontré", "demontre", "découvert", "decouvert",
    "appris", "compris", "appris", "vu", "vue",
    "trouve", "trouvé", "garde", "gardé", "respecte", "respecté",
    "ouvre", "ouvert", "ferme", "fermé",
    "voulu", "su", "pu", "du", "dû",
    "tente", "tenté", "essaye", "essayé", "reussi", "réussi", "echoue", "échoué",
    "rendu", "fourni", "fournie", "soumis", "soumise",
    "constate", "constaté", "etabli", "établi", "ete", "été",
]

def apply_fixes(text: str) -> str:
    # 1. Word-by-word replacements (sort by length desc to avoid partial matches)
    items = sorted(WORD_FIXES.items(), key=lambda kv: -len(kv[0]))
    for src, dst in items:
        if src == dst:
            continue
        pattern = r"\b" + re.escape(src) + r"\b"
        text = re.sub(pattern, dst, text)

    # 2. Preposition "a" -> "a"
    # Strategie : remplacer " a X" -> " a X" pour tous les contextes courants,
    # sauf quand "a" est l'auxiliaire (suivi d'un participe passe).
    #
    # Etape A : marque "Y a PARTICIPE" (auxiliaire) avec un sentinel APRES le 'a'
    # pour que les patterns suivants ne le matchent pas.
    # Sentinel : tilde + Z (improbable dans le texte).
    SENTINEL = "~Z~"
    followers_pattern = "(?:" + "|".join(
        re.escape(f) for f in AVOIR_FOLLOWERS
    ) + ")"
    text = re.sub(
        r"\b([a-zA-Z'\-]+)\s+a\s+(" + followers_pattern + r")\b",
        lambda m: f"{m.group(1)} a{SENTINEL} {m.group(2)}",
        text,
    )
    # Cas "n'a ", "qu'a " (apostrophe directement)
    text = re.sub(
        r"(n|qu|qui|c|s)'a\s+(" + followers_pattern + r")\b",
        lambda m: f"{m.group(1)}'a{SENTINEL} {m.group(2)}",
        text,
    )

    # Etape B : remplace " a " -> " a "  partout sauf protection sentinel
    # Patterns specifiques (preposition suivie d'article/determinant/nombre/etc.)
    PREPOSITION_PATTERNS = [
        (r"(\s)a la\b", r"\1à la"),
        (r"(\s)a l'", r"\1à l'"),
        (r"(\s)a une\b", r"\1à une"),
        (r"(\s)a un\b", r"\1à un"),
        (r"(\s)a ces?\b", r"\1à ce"),  # a ce / a ces
        (r"(\s)a ces\b", r"\1à ces"),
        (r"(\s)a cet\b", r"\1à cet"),
        (r"(\s)a cette\b", r"\1à cette"),
        (r"(\s)a son\b", r"\1à son"),
        (r"(\s)a sa\b", r"\1à sa"),
        (r"(\s)a ses\b", r"\1à ses"),
        (r"(\s)a leur(s)?\b", r"\1à leur\2"),
        (r"(\s)a mon\b", r"\1à mon"),
        (r"(\s)a ma\b", r"\1à ma"),
        (r"(\s)a mes\b", r"\1à mes"),
        (r"(\s)a notre\b", r"\1à notre"),
        (r"(\s)a nos\b", r"\1à nos"),
        (r"(\s)a votre\b", r"\1à votre"),
        (r"(\s)a vos\b", r"\1à vos"),
        (r"(\s)a tout\b", r"\1à tout"),
        (r"(\s)a tous\b", r"\1à tous"),
        (r"(\s)a toute\b", r"\1à toute"),
        (r"(\s)a toutes\b", r"\1à toutes"),
        (r"(\s)a chaque\b", r"\1à chaque"),
        (r"(\s)a chacun\b", r"\1à chacun"),
        (r"(\s)a quelques\b", r"\1à quelques"),
        (r"(\s)a plusieurs\b", r"\1à plusieurs"),
        (r"(\s)a partir\b", r"\1à partir"),
        (r"(\s)a travers\b", r"\1à travers"),
        (r"(\s)a propos\b", r"\1à propos"),
        (r"(\s)a savoir\b", r"\1à savoir"),
        (r"(\s)a defaut\b", r"\1à défaut"),
        (r"(\s)a venir\b", r"\1à venir"),
        (r"(\s)a faible\b", r"\1à faible"),
        (r"(\s)a forte\b", r"\1à forte"),
        (r"(\s)a fort\b", r"\1à fort"),
        (r"(\s)a fortes\b", r"\1à fortes"),
        (r"(\s)a faibles\b", r"\1à faibles"),
        (r"(\s)a horizon\b", r"\1à horizon"),
        (r"(\s)a court\b", r"\1à court"),
        (r"(\s)a long\b", r"\1à long"),
        (r"(\s)a moyen\b", r"\1à moyen"),
        (r"(\s)a date\b", r"\1à date"),
        (r"(\s)a niveau\b", r"\1à niveau"),
        (r"(\s)a peine\b", r"\1à peine"),
        (r"(\s)a part\b", r"\1à part"),
        (r"(\s)a parts\b", r"\1à parts"),
        (r"(\s)a deux\b", r"\1à deux"),
        (r"(\s)a trois\b", r"\1à trois"),
        (r"(\s)a quatre\b", r"\1à quatre"),
        (r"(\s)a cinq\b", r"\1à cinq"),
        (r"(\s)a six\b", r"\1à six"),
        (r"(\s)a sept\b", r"\1à sept"),
        (r"(\s)a huit\b", r"\1à huit"),
        (r"(\s)a neuf\b", r"\1à neuf"),
        (r"(\s)a dix\b", r"\1à dix"),
        (r"(\s)a cent\b", r"\1à cent"),
        (r"(\s)a mille\b", r"\1à mille"),
        (r"(\s)a million\b", r"\1à million"),
        # nombres
        (r"(\s)a (\d)", r"\1à \2"),
        # "compare a", "compares a", "remplacer a", etc.
        (r"(\s)a venir\b", r"\1à venir"),
        # "a l'horizon", "a l'echelle", etc deja capture par "a l'"
        # Mots usuels apres "a" : ETAT, LIEU, ECHELLE
        (r"(\s)a echelle\b", r"\1à échelle"),
        (r"(\s)a maille\b", r"\1à maille"),
        # Quelques tournures
        (r"(\s)a hauteur\b", r"\1à hauteur"),
        (r"(\s)a charge\b", r"\1à charge"),
        (r"(\s)a propos\b", r"\1à propos"),
        (r"(\s)a defaut\b", r"\1à défaut"),
        # Cas debut de phrase ou apres ponctuation
        (r"(^|[.;:,\(])\s*A la\b", r"\1 À la"),
        (r"(^|[.;:,\(])\s*A l'", r"\1 À l'"),
        # "egard a" -> "egard a" wait this would have been caught
    ]
    for pat, rep in PREPOSITION_PATTERNS:
        text = re.sub(pat, rep, text)

    # Etape C : restaure le sentinel
    text = text.replace(SENTINEL, "")

    return text


def main():
    print(f"[fix] Lecture {TARGET}")
    src = TARGET.read_text(encoding="utf-8")
    print(f"[fix] Avant : {len(src)} caracteres")
    n_before = sum(text in src for text in WORD_FIXES.keys() if text != WORD_FIXES[text])
    fixed = apply_fixes(src)
    print(f"[fix] Apres : {len(fixed)} caracteres")
    TARGET.write_text(fixed, encoding="utf-8")
    print(f"[fix] OK - {TARGET} mis a jour")


if __name__ == "__main__":
    main()
